version: '3'
services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # dev only
    ports:
      - "9200:9200"
  filebeat:
    build: ./filebeat
    image: filebeat
    container_name: filebeat
    depends_on:
      - elasticsearch
      - kibana
    volumes: 
      - nginx-logs:/var/log/nginx
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    ports:
      - "5601:5601"
  metricbeat:
    build: ./metricbeat
    image: metricbeat
    container_name: metricbeat
    depends_on:
      - elasticsearch
      - kibana
  nginx: 
    build: ./nginx
    image: nginx-server
    container_name: nginx-server
    ports:
      - "8888:80"
    volumes:
      - nginx-logs:/var/log/nginx
volumes:
  nginx-logs:
